package Final;


import java.awt.*;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;




public class main extends javax.swing.JFrame {


    //Creates new form main
    public main() {
        initComponents();
         isLoggin(false);
    }
  public void isLoggin(boolean b) {
        Login_menu.setEnabled(!b);
        Logout_menu.setEnabled(b);
        if (b) {
            jLabel1.setText("You logged in as: ");
            tab_Home.setVisible(true);
        } else {
            jLabel1.setText("welcome to public account.");
            tab_Home.setVisible(false);
            panel_Home.setVisible(true);
            panel_Calendar.setVisible(false);
            panel_Dashboard.setVisible(false);
            panel_Chats.setVisible(false);
        }



       
           

        }

       




    //Calendar functions


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        desktopPane = new javax.swing.JDesktopPane();
        panel_Home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tab_Home = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panel_Calendar = new javax.swing.JPanel();
        javax.swing.JPanel jPanel8 = new javax.swing.JPanel();
        list = new javax.swing.JPanel();
        newevent = new javax.swing.JButton();
        panel_Dashboard = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        panel_Chats = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        navigation = new javax.swing.JPanel();
        Home_btn = new javax.swing.JButton();
        Dashboard_btn = new javax.swing.JButton();
        Calendar_btn = new javax.swing.JButton();
        Chat_btn = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        Account_menu = new javax.swing.JMenu();
        Login_menu = new javax.swing.JMenuItem();
        Logout_menu = new javax.swing.JMenuItem();
        register = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lesson Planner");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        desktopPane.setDragMode(javax.swing.JDesktopPane.OUTLINE_DRAG_MODE);
        desktopPane.setBackground(Color.decode("#d1d2dd"));
        desktopPane.setOpaque(true);

        panel_Home.setBackground(Color.decode("#d1d2dd"));

        jLabel1.setText("jLabel1");

        jLabel8.setText("Subjects");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        tab_Home.addTab("Portfolio", jPanel3);

        jLabel4.setText("Name:");

        jLabel5.setText("Department:");

        jLabel6.setText("level of profession:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        tab_Home.addTab("Profile Details", jPanel2);

        javax.swing.GroupLayout panel_HomeLayout = new javax.swing.GroupLayout(panel_Home);
        panel_Home.setLayout(panel_HomeLayout);
        panel_HomeLayout.setHorizontalGroup(
            panel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_HomeLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(tab_Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1000, Short.MAX_VALUE))
        );
        panel_HomeLayout.setVerticalGroup(
            panel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_HomeLayout.createSequentialGroup()
                .addGroup(panel_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_HomeLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel1))
                    .addGroup(panel_HomeLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(tab_Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(500, Short.MAX_VALUE))
        );

        panel_Calendar.setBackground(Color.decode("#778da9"));
        panel_Calendar.setMaximumSize(new java.awt.Dimension(600, 600));
        panel_Calendar.add(new Calendar());

        jPanel8.setLayout(new java.awt.GridLayout(0, 7));

        newevent.setBackground(Color.decode("#778da9"));
        newevent.setText("NEW");
        newevent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neweventActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listLayout = new javax.swing.GroupLayout(list);
        list.setLayout(listLayout);
        listLayout.setHorizontalGroup(
            listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newevent, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        );
        listLayout.setVerticalGroup(
            listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listLayout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addComponent(newevent, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panel_CalendarLayout = new javax.swing.GroupLayout(panel_Calendar);
        panel_Calendar.setLayout(panel_CalendarLayout);
        panel_CalendarLayout.setHorizontalGroup(
            panel_CalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_CalendarLayout.createSequentialGroup()
                .addContainerGap(800, Short.MAX_VALUE)
                .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_CalendarLayout.setVerticalGroup(
            panel_CalendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_CalendarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        panel_Dashboard.setBackground(Color.decode("#778da9"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("In Progress", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Achieved", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Objectives", jPanel6);

        javax.swing.GroupLayout panel_DashboardLayout = new javax.swing.GroupLayout(panel_Dashboard);
        panel_Dashboard.setLayout(panel_DashboardLayout);
        panel_DashboardLayout.setHorizontalGroup(
            panel_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_DashboardLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_DashboardLayout.setVerticalGroup(
            panel_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_DashboardLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(400, Short.MAX_VALUE))
        );

        panel_Chats.setBackground(Color.decode("#778da9"));
        panel_Chats.setOpaque(true);


        jLabel2.setFont(new Font("Times New Roman",Font.PLAIN,18)); // NOI18N
        jLabel2.setText("LESSON PLANNER FOR TEACHERS");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("MOTTO: Elimu Ni Mwanagza");

        navigation.setBackground(Color.decode("#274472"));
        navigation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home_btn.setBackground(Color.decode("#274472"));
        Home_btn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Home_btn.setForeground(new java.awt.Color(255, 255, 255));
        Home_btn.setText("Home");
        Home_btn.setBorder(null);
        Home_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home_btnActionPerformed(evt);
            }
        });
        navigation.add(Home_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 143, 48));

        Dashboard_btn.setBackground(Color.decode("#274472"));
        Dashboard_btn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Dashboard_btn.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard_btn.setText("Dashboard");
        Dashboard_btn.setBorder(null);
        Dashboard_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dashboard_btnActionPerformed(evt);
            }
        });
        navigation.add(Dashboard_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 127, 143, 45));

        Calendar_btn.setBackground(Color.decode("#274472"));
        Calendar_btn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Calendar_btn.setForeground(new java.awt.Color(255, 255, 255));
        Calendar_btn.setText("Calendar");
        Calendar_btn.setBorder(null);
        Calendar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calendar_btnActionPerformed(evt);
            }
        });
        navigation.add(Calendar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 205, 143, 43));

        Chat_btn.setBackground(Color.decode("#274472"));
        Chat_btn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Chat_btn.setForeground(new java.awt.Color(255, 255, 255));
        Chat_btn.setText("Public Chats");
        Chat_btn.setBorder(null);
        Chat_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Chat_btnActionPerformed(evt);
            }
        });
        navigation.add(Chat_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 282, 143, 50));

        desktopPane.setLayer(panel_Home, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(panel_Calendar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(panel_Dashboard, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(panel_Chats, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(navigation, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addComponent(navigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addGap(381, 381, 381)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addGap(437, 437, 437)
                        .addComponent(jLabel3))
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(panel_Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_Calendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 850, Short.MAX_VALUE)
                .addComponent(panel_Chats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addGap(466, 466, 466)
                        .addComponent(panel_Chats, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel_Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panel_Calendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 211, Short.MAX_VALUE))
            .addComponent(navigation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(desktopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2720, 730));

        menuBar.setBackground(new java.awt.Color(0, 153, 153));

        Account_menu.setBackground(Color.decode("#d1d2dd"));
        Account_menu.setText("Account");
        Account_menu.setAutoscrolls(true);
        Account_menu.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Account_menu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Account_menu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        Login_menu.setBackground(new java.awt.Color(0, 153, 153));
        Login_menu.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        Login_menu.setText("Login");
        Login_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_menuActionPerformed(evt);
            }
        });
        Account_menu.add(Login_menu);

        Logout_menu.setBackground(new java.awt.Color(0, 153, 153));
        Logout_menu.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        Logout_menu.setText("Logout");
        Logout_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_menuActionPerformed(evt);
            }
        });
        Account_menu.add(Logout_menu);

        register.setBackground(Color.decode("#BDDDFC"));
        register.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        Account_menu.add(register);

        menuBar.add(Account_menu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Login_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_menuActionPerformed
        // TODO add your handling code here:
        LoginPopup loginPopups = new LoginPopup(null, true, this);
        loginPopups.show();
    }//GEN-LAST:event_Login_menuActionPerformed

    private void Logout_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_menuActionPerformed
        // TODO add your handling code here:
         isLoggin(false);
    }//GEN-LAST:event_Logout_menuActionPerformed

    private void Home_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_btnActionPerformed
        // TODO add your handling code here:

        panel_Home.setVisible(true);
        panel_Calendar.setVisible(false);
        panel_Dashboard.setVisible(false);
        panel_Chats.setVisible(false);
    }//GEN-LAST:event_Home_btnActionPerformed

    private void Dashboard_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dashboard_btnActionPerformed
        panel_Home.setVisible(false);
        panel_Calendar.setVisible(false);
        panel_Dashboard.setVisible(true);
        panel_Chats.setVisible(false);
    }//GEN-LAST:event_Dashboard_btnActionPerformed

    private void Chat_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Chat_btnActionPerformed
        // TODO add your handling code here:
        panel_Home.setVisible(false);
        panel_Calendar.setVisible(false);
        panel_Dashboard.setVisible(false);
        panel_Chats.setVisible(true);
    }//GEN-LAST:event_Chat_btnActionPerformed

    private void Calendar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calendar_btnActionPerformed
        // TODO add your handling code here:
        panel_Home.setVisible(false);
        panel_Calendar.setVisible(true);
        panel_Dashboard.setVisible(false);
        panel_Chats.setVisible(false);
    }//GEN-LAST:event_Calendar_btnActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
         new Reg();
    }//GEN-LAST:event_registerActionPerformed

    private void neweventActionPerformed(java.awt.event.ActionEvent evt) {                                         
       new Events();
    }
    
//Calendar section

        /* Create and display the form */
         public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (UnsupportedLookAndFeelException e) {
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }

             

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new main().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Account_menu;
    private javax.swing.JButton Calendar_btn;
    private javax.swing.JButton Chat_btn;
    private javax.swing.JButton Dashboard_btn;
    private javax.swing.JButton Home_btn;
    private javax.swing.JMenuItem Login_menu;
    private javax.swing.JMenuItem Logout_menu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel list;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel navigation;
    private javax.swing.JButton newevent;
    private javax.swing.JPanel panel_Calendar;
    private javax.swing.JPanel panel_Chats;
    private javax.swing.JPanel panel_Dashboard;
    private javax.swing.JPanel panel_Home;
    private javax.swing.JMenuItem register;
    private javax.swing.JTabbedPane tab_Home;
    // End of variables declaration//GEN-END:variables
    }
